"use server";
import { z } from "zod";
import { Prisma } from "@prisma/client";
import { createBooking } from "@/lib/booking";
import { calculateStay } from "@/lib/pricing";
import { db } from "@/lib/prisma";
const schema=z.object({tenantSlug:z.string().min(1),propertySlug:z.string().min(1),checkIn:z.coerce.date(),checkOut:z.coerce.date(),guests:z.coerce.number().int().positive(),clientName:z.string().trim().min(2).max(120),clientEmail:z.string().email(),clientPhone:z.string().max(40).optional(),clientMessage:z.string().max(2000).optional(),optionIds:z.array(z.string()).default([]),promoCode:z.string().max(60).optional()});
async function findProperty(tenantSlug:string,propertySlug:string){return db.property.findFirst({where:{slug:propertySlug,tenant:{slug:tenantSlug,status:"ACTIVE"},isActive:true,isPublished:true},include:{pricingRules:{where:{isActive:true}},tenant:{include:{settings:true,options:{where:{isActive:true}}}},blockedDates:true}});}
export async function getBookingQuote(input:Pick<z.input<typeof schema>,"tenantSlug"|"propertySlug"|"checkIn"|"checkOut"|"guests"|"optionIds"|"promoCode">){const d=schema.pick({tenantSlug:true,propertySlug:true,checkIn:true,checkOut:true,guests:true,optionIds:true,promoCode:true}).parse(input);if(d.checkOut<=d.checkIn)throw new Error("INVALID_DATES");const p=await findProperty(d.tenantSlug,d.propertySlug);if(!p)throw new Error("PROPERTY_NOT_FOUND");const overlap=await db.booking.findFirst({where:{propertyId:p.id,OR:[{status:"CONFIRMED"},{status:"PENDING",expiresAt:{gt:new Date()}}],checkIn:{lt:d.checkOut},checkOut:{gt:d.checkIn}});const blocked=p.blockedDates.some(b=>b.startDate<d.checkOut&&b.endDate>d.checkIn);const selected=p.tenant.options.filter(o=>d.optionIds.includes(o.id));const optionTotals=selected.reduce((s,o)=>s.add(o.price),new Prisma.Decimal(0));let discount=new Prisma.Decimal(0);if(d.promoCode){const promo=await db.promoCode.findFirst({where:{tenantId:p.tenantId,code:d.promoCode.trim().toUpperCase(),isActive:true,OR:[{propertyId:null},{propertyId:p.id}]}});if(promo&&(!promo.maxUses||promo.usedCount<promo.maxUses)&&(!promo.validFrom||promo.validFrom<=d.checkIn)&&(!promo.validUntil||promo.validUntil>=d.checkOut)){const base=calculateStay({baseRate:p.baseNightlyRate,rules:p.pricingRules,checkIn:d.checkIn,checkOut:d.checkOut,cleaningFee:p.cleaningFee,optionTotals});if(!promo.minNights||base.nights>=promo.minNights)discount=promo.type==="PERCENTAGE"?base.subtotal.mul(promo.value).div(100):Prisma.Decimal.min(promo.value,base.subtotal);}}
const nights=Math.ceil((d.checkOut.getTime()-d.checkIn.getTime())/86400000);const touristTax=p.tenant.settings?.touristTaxEnabled?new Prisma.Decimal(p.tenant.settings.touristTaxPerNight).mul(nights*d.guests):new Prisma.Decimal(0);const calc=calculateStay({baseRate:p.baseNightlyRate,rules:p.pricingRules,checkIn:d.checkIn,checkOut:d.checkOut,cleaningFee:p.cleaningFee,optionTotals,discount,touristTax});return{nights:calc.nights,subtotal:calc.subtotal.toString(),discount:calc.discount.toString(),cleaningFee:calc.cleaningFee.toString(),optionTotals:calc.optionTotals.toString(),touristTax:calc.touristTax.toString(),total:calc.total.toString(),available:!overlap&&!blocked&&d.guests<=p.maxGuests,options:p.tenant.options.map(o=>({id:o.id,name:o.name,price:o.price.toString(),unit:o.unit})),currency:p.tenant.settings?.currency??"EUR"};}
export async function submitBooking(input:z.input<typeof schema>){const d=schema.parse(input);const p=await findProperty(d.tenantSlug,d.propertySlug);if(!p)throw new Error("PROPERTY_NOT_FOUND");if(d.guests>p.maxGuests)throw new Error("TOO_MANY_GUESTS");return createBooking({...d,tenantId:p.tenantId,propertyId:p.id});}
