"use server";
import { z } from "zod";
import { db } from "@/lib/prisma";
import { requireHostTenant } from "@/lib/authz";
const schema=z.object({propertyId:z.string().optional(),name:z.string().trim().min(2).max(120),startDate:z.coerce.date().optional(),endDate:z.coerce.date().optional(),weekdays:z.array(z.number().int().min(0).max(6)).default([]),nightlyRate:z.coerce.number().positive().optional(),multiplier:z.coerce.number().positive().optional(),minNights:z.coerce.number().int().positive().optional(),priority:z.coerce.number().int().min(-100).max(1000).default(0)});
function validateRule(d:z.infer<typeof schema>){if(!d.nightlyRate&&!d.multiplier)throw new Error("PRICE_RULE_NEEDS_RATE");if(d.nightlyRate&&d.multiplier)throw new Error("PRICE_RULE_AMBIGUOUS");if(d.startDate&&d.endDate&&d.endDate<d.startDate)throw new Error("INVALID_DATES");}
export async function listPricingRules(propertyId?:string){const {tenant}=await requireHostTenant();if(propertyId&&!await db.property.findFirst({where:{id:propertyId,tenantId:tenant.id}}))throw new Error("PROPERTY_NOT_FOUND");return db.pricingRule.findMany({where:{tenantId:tenant.id,propertyId:propertyId??undefined},orderBy:[{priority:"desc"},{createdAt:"desc"}]});}
export async function createPricingRule(input:z.input<typeof schema>){const {tenant}=await requireHostTenant();const d=schema.parse(input);validateRule(d);if(d.propertyId&&!await db.property.findFirst({where:{id:d.propertyId,tenantId:tenant.id}}))throw new Error("PROPERTY_NOT_FOUND");return db.pricingRule.create({data:{...d,tenantId:tenant.id,propertyId:d.propertyId??null}});}
export async function updatePricingRule(id:string,input:z.input<typeof schema>){const {tenant}=await requireHostTenant();const d=schema.parse(input);validateRule(d);if(!await db.pricingRule.findFirst({where:{id,tenantId:tenant.id}}))throw new Error("PRICING_RULE_NOT_FOUND");if(d.propertyId&&!await db.property.findFirst({where:{id:d.propertyId,tenantId:tenant.id}}))throw new Error("PROPERTY_NOT_FOUND");return db.pricingRule.update({where:{id},data:{...d,propertyId:d.propertyId??null}});}
export async function deletePricingRule(id:string){const {tenant}=await requireHostTenant();const r=await db.pricingRule.deleteMany({where:{id,tenantId:tenant.id}});if(!r.count)throw new Error("PRICING_RULE_NOT_FOUND");return {ok:true};}
export async function setPricingRuleActive(id:string,isActive:boolean){const {tenant}=await requireHostTenant();const r=await db.pricingRule.updateMany({where:{id,tenantId:tenant.id},data:{isActive}});if(!r.count)throw new Error("PRICING_RULE_NOT_FOUND");return {ok:true};}
